version: "3.9"
services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
      target: development
    container_name: api
    command: yarn start:dev
    volumes:
      - .:/usr/src/app
      - node_modules:/usr/src/app/node_modules
    ports:
      - "${PORT}:${PORT}"
    env_file:
      - .env

volumes:
  node_modules:
